/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as ArbRouteImport } from './routes/arb'
import { Route as BilanRouteImport } from './routes/bilan'
import { Route as BotRouteImport } from './routes/bot'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as ConvertRouteImport } from './routes/convert'
import { Route as CorrelationRouteImport } from './routes/correlation'
import { Route as DcaRouteImport } from './routes/dca'
import { Route as FiscalRouteImport } from './routes/fiscal'
import { Route as HeatmapRouteImport } from './routes/heatmap'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as ScreenerRouteImport } from './routes/screener'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StakingRouteImport } from './routes/staking'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TradePairRouteImport } from './routes/trade.$pair'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ArbRoute = ArbRouteImport.update({
  id: '/arb',
  path: '/arb',
  getParentRoute: () => rootRouteImport,
} as any)
const BilanRoute = BilanRouteImport.update({
  id: '/bilan',
  path: '/bilan',
  getParentRoute: () => rootRouteImport,
} as any)
const BotRoute = BotRouteImport.update({
  id: '/bot',
  path: '/bot',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvertRoute = ConvertRouteImport.update({
  id: '/convert',
  path: '/convert',
  getParentRoute: () => rootRouteImport,
} as any)
const CorrelationRoute = CorrelationRouteImport.update({
  id: '/correlation',
  path: '/correlation',
  getParentRoute: () => rootRouteImport,
} as any)
const DcaRoute = DcaRouteImport.update({
  id: '/dca',
  path: '/dca',
  getParentRoute: () => rootRouteImport,
} as any)
const FiscalRoute = FiscalRouteImport.update({
  id: '/fiscal',
  path: '/fiscal',
  getParentRoute: () => rootRouteImport,
} as any)
const HeatmapRoute = HeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenerRoute = ScreenerRouteImport.update({
  id: '/screener',
  path: '/screener',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StakingRoute = StakingRouteImport.update({
  id: '/staking',
  path: '/staking',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TradePairRoute = TradePairRouteImport.update({
  id: '/trade/$pair',
  path: '/trade/$pair',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/arb': typeof ArbRoute
  '/bilan': typeof BilanRoute
  '/bot': typeof BotRoute
  '/calculator': typeof CalculatorRoute
  '/connect': typeof ConnectRoute
  '/convert': typeof ConvertRoute
  '/correlation': typeof CorrelationRoute
  '/dca': typeof DcaRoute
  '/fiscal': typeof FiscalRoute
  '/heatmap': typeof HeatmapRoute
  '/journal': typeof JournalRoute
  '/orders': typeof OrdersRoute
  '/risk': typeof RiskRoute
  '/screener': typeof ScreenerRoute
  '/settings': typeof SettingsRoute
  '/staking': typeof StakingRoute
  '/tools': typeof ToolsRoute
  '/wallet': typeof WalletRoute
  '/trade/$pair': typeof TradePairRoute
  '/api/v1/$': typeof ApiV1SplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/arb': typeof ArbRoute
  '/bilan': typeof BilanRoute
  '/bot': typeof BotRoute
  '/calculator': typeof CalculatorRoute
  '/connect': typeof ConnectRoute
  '/convert': typeof ConvertRoute
  '/correlation': typeof CorrelationRoute
  '/dca': typeof DcaRoute
  '/fiscal': typeof FiscalRoute
  '/heatmap': typeof HeatmapRoute
  '/journal': typeof JournalRoute
  '/orders': typeof OrdersRoute
  '/risk': typeof RiskRoute
  '/screener': typeof ScreenerRoute
  '/settings': typeof SettingsRoute
  '/staking': typeof StakingRoute
  '/tools': typeof ToolsRoute
  '/wallet': typeof WalletRoute
  '/trade/$pair': typeof TradePairRoute
  '/api/v1/$': typeof ApiV1SplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/arb': typeof ArbRoute
  '/bilan': typeof BilanRoute
  '/bot': typeof BotRoute
  '/calculator': typeof CalculatorRoute
  '/connect': typeof ConnectRoute
  '/convert': typeof ConvertRoute
  '/correlation': typeof CorrelationRoute
  '/dca': typeof DcaRoute
  '/fiscal': typeof FiscalRoute
  '/heatmap': typeof HeatmapRoute
  '/journal': typeof JournalRoute
  '/orders': typeof OrdersRoute
  '/risk': typeof RiskRoute
  '/screener': typeof ScreenerRoute
  '/settings': typeof SettingsRoute
  '/staking': typeof StakingRoute
  '/tools': typeof ToolsRoute
  '/wallet': typeof WalletRoute
  '/trade/$pair': typeof TradePairRoute
  '/api/v1/$': typeof ApiV1SplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/arb'
    | '/bilan'
    | '/bot'
    | '/calculator'
    | '/connect'
    | '/convert'
    | '/correlation'
    | '/dca'
    | '/fiscal'
    | '/heatmap'
    | '/journal'
    | '/orders'
    | '/risk'
    | '/screener'
    | '/settings'
    | '/staking'
    | '/tools'
    | '/wallet'
    | '/trade/$pair'
    | '/api/v1/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/arb'
    | '/bilan'
    | '/bot'
    | '/calculator'
    | '/connect'
    | '/convert'
    | '/correlation'
    | '/dca'
    | '/fiscal'
    | '/heatmap'
    | '/journal'
    | '/orders'
    | '/risk'
    | '/screener'
    | '/settings'
    | '/staking'
    | '/tools'
    | '/wallet'
    | '/trade/$pair'
    | '/api/v1/$'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/arb'
    | '/bilan'
    | '/bot'
    | '/calculator'
    | '/connect'
    | '/convert'
    | '/correlation'
    | '/dca'
    | '/fiscal'
    | '/heatmap'
    | '/journal'
    | '/orders'
    | '/risk'
    | '/screener'
    | '/settings'
    | '/staking'
    | '/tools'
    | '/wallet'
    | '/trade/$pair'
    | '/api/v1/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  ArbRoute: typeof ArbRoute
  BilanRoute: typeof BilanRoute
  BotRoute: typeof BotRoute
  CalculatorRoute: typeof CalculatorRoute
  ConnectRoute: typeof ConnectRoute
  ConvertRoute: typeof ConvertRoute
  CorrelationRoute: typeof CorrelationRoute
  DcaRoute: typeof DcaRoute
  FiscalRoute: typeof FiscalRoute
  HeatmapRoute: typeof HeatmapRoute
  JournalRoute: typeof JournalRoute
  OrdersRoute: typeof OrdersRoute
  RiskRoute: typeof RiskRoute
  ScreenerRoute: typeof ScreenerRoute
  SettingsRoute: typeof SettingsRoute
  StakingRoute: typeof StakingRoute
  ToolsRoute: typeof ToolsRoute
  WalletRoute: typeof WalletRoute
  TradePairRoute: typeof TradePairRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arb': {
      id: '/arb'
      path: '/arb'
      fullPath: '/arb'
      preLoaderRoute: typeof ArbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bilan': {
      id: '/bilan'
      path: '/bilan'
      fullPath: '/bilan'
      preLoaderRoute: typeof BilanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bot': {
      id: '/bot'
      path: '/bot'
      fullPath: '/bot'
      preLoaderRoute: typeof BotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convert': {
      id: '/convert'
      path: '/convert'
      fullPath: '/convert'
      preLoaderRoute: typeof ConvertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/correlation': {
      id: '/correlation'
      path: '/correlation'
      fullPath: '/correlation'
      preLoaderRoute: typeof CorrelationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dca': {
      id: '/dca'
      path: '/dca'
      fullPath: '/dca'
      preLoaderRoute: typeof DcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fiscal': {
      id: '/fiscal'
      path: '/fiscal'
      fullPath: '/fiscal'
      preLoaderRoute: typeof FiscalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heatmap': {
      id: '/heatmap'
      path: '/heatmap'
      fullPath: '/heatmap'
      preLoaderRoute: typeof HeatmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screener': {
      id: '/screener'
      path: '/screener'
      fullPath: '/screener'
      preLoaderRoute: typeof ScreenerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staking': {
      id: '/staking'
      path: '/staking'
      fullPath: '/staking'
      preLoaderRoute: typeof StakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade/$pair': {
      id: '/trade/$pair'
      path: '/trade/$pair'
      fullPath: '/trade/$pair'
      preLoaderRoute: typeof TradePairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  ArbRoute: ArbRoute,
  BilanRoute: BilanRoute,
  BotRoute: BotRoute,
  CalculatorRoute: CalculatorRoute,
  ConnectRoute: ConnectRoute,
  ConvertRoute: ConvertRoute,
  CorrelationRoute: CorrelationRoute,
  DcaRoute: DcaRoute,
  FiscalRoute: FiscalRoute,
  HeatmapRoute: HeatmapRoute,
  JournalRoute: JournalRoute,
  OrdersRoute: OrdersRoute,
  RiskRoute: RiskRoute,
  ScreenerRoute: ScreenerRoute,
  SettingsRoute: SettingsRoute,
  StakingRoute: StakingRoute,
  ToolsRoute: ToolsRoute,
  WalletRoute: WalletRoute,
  TradePairRoute: TradePairRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
